### PR TITLE
Added RL Notes

### PR DESCRIPTION
**Pull request by 5iri**
## Added RL Notes

Contains most of the content which was taught during the offline lecture that happened on last saturday conducted by alqama and ansh.

### CODE REVIEW

**Comment by vovw** [comment]
Screenshot 2024-10-09 at 11 08 13 PM


can you fix this please ??

**Comment by aPR0T0** [comment]
@vovw are the issues fixed?

**Comment by vovw** [comment]
> @vovw are the issues fixed?
yep, all good.

the markdown on github acts weird for some reason but i am thinking of migrating all the notes to the website using pandoc later this week.

but LGTM

**Review by vovw — APPROVED** [review]
LGTM

**Pull request merged**
